
/*
  List Action From Global Merge
*/
export const GLB_MERGE_CHANGE_DATA_SOURCE = 'GLB_MERGE_CHANGE_DATA_SOURCE'
export const GLB_MERGE_CHANGE_OBJECT  = 'GLB_MERGE_CHANGE_OBJECT'
export const GLB_MERGE_CHANGE_FILTER  = 'GLB_MERGE_CHANGE_FILTER'
export const GLB_MERGE_TICK_FIELD   = 'GLB_MERGE_TICK_FIELD'
export const GLB_MERGE_FORMULA   = 'GLB_MERGE_FORMULA'
export const GLB_MERGE_CHANGE_MAP = 'GLB_MERGE_CHANGE_MAP' //Changing Selectbox in DS 2
export const GLB_MERGE_SAVE = 'GLB_MERGE_SAVE'
